# Generated by Django 5.2.2 on 2025-06-17 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='user',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordendetalle',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='ordendetalle',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.orden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.CreateModel(
            name='AtributoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='store.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Código interno o UPC opcional', max_length=100, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Si varía de precio respecto al Producto', max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='store.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='variante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.variante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='variante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.variante'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VarianteAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.atributovalor')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='store.variante')),
            ],
            options={
                'unique_together': {('variante', 'atributo_valor')},
            },
        ),
    ]
