# Generated by Django 5.2.2 on 2025-06-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_atributo_rename_user_orden_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='producto',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='store.producto'),
        ),
    ]
