# Generated by Django 5.2.2 on 2025-06-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carritoproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='precio_mayorista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
