# Generated by Django 5.2.2 on 2025-06-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cliente_is_active_cliente_is_admin_and_more'),
        ('store', '0003_remove_wishlist_producto_wishlist_productos'),
    ]

    operations = [
    ]
