# Generated by Django 5.2.2 on 2025-06-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variante_precio_mayorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_mayorista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
