### obtener productos
GET http://127.0.0.1:8000/api/productos


### Crear productos
POST http://127.0.0.1:8000/api/productos/crear/
Content-Type: application/json

{
  "nombre": "New Balance",
  "descripcion": "Tenis para correr",
  "precio": 119.99,
  "categoria_id": 1,
  "genero": "Unisex",
  "en_oferta": false,
  "imagen": "newBalance.jpg",
  "stock": 35
}

###
POST http://127.0.0.1:8000/api/productos/update/3/
Content-Type: application/x-www-form-urlencoded

nombre=AirMax97&stock=35

### DELETE
DELETE http://127.0.0.1:8000/api/productos/delete/2/