### obtener productos
GET http://127.0.0.1:8000/api/productos


### Crear productos
POST http://127.0.0.1:8000/api/productos/crear/
Content-Type: application/json

{
  "nombre": "Forumm",
  "descripcion": "Tenis para correr",
  "precio": 119.99,
  "categoria_id": 1,
  "genero": "Unisex",
  "en_oferta": false,
  "imagen": "newBalance.jpg",
  "stock": 35
}

###
POST http://127.0.0.1:8000/api/productos/update/3/
Content-Type: application/x-www-form-urlencoded

nombre=AirForce&stock=30

### DELETE
DELETE http://127.0.0.1:8000/api/productos/delete/2/

### GET clientes
GET http://127.0.0.1:8000/clientes

### Crear cliente

POST http://127.0.0.1:8000/clientes/crear
Content-Type: application/json

{
  "username": "New Balance",
  "password": "Tenis para correr"
}

###

POST http://127.0.0.1:8000/user/create/
Content-Type: application/json

{
  "username": "angel",
  "password": "123456",
  "role": "admin"
}


###
POST http://127.0.0.1:8000/clientes/update/1
Content-Type: application/json

{
  "username": "Angel"
}



### Crear contacto

POST http://127.0.0.1:8000/contact/create/1
Content-Type: application/json

{
  "nombre": "Angel Adrian",
  "email": "adrian@gmail.com",
  "mensaje": "Hola hoña"
}


###
POST http://127.0.0.1:8000/contact/update/1
Content-Type: application/json

{
  "email": "adrian@gmail.com"
}

###
GET http://127.0.0.1:8000/user/get

###
POST http://127.0.0.1:8000/user/create
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "role": "Admin"
}




### Crear un carrito para el cliente #5
POST http://127.0.0.1:8000/api/carrito/create/5/ HTTP/1.1
Content-Type: application/json

{
  "status": "activo"
}

###

### Actualizar solo el status del carrito #7 (PATCH)
PATCH http://127.0.0.1:8000/api/carrito/7/ HTTP/1.1
Content-Type: application/json

{
  "status": "procesando"
}

###

### Actualizar cliente y status del carrito #7 (PUT)
PUT http://127.0.0.1:8000/api/carrito/7/ HTTP/1.1
Content-Type: application/json

{
  "cliente_id": 3,
  "status":     "pagado"
}


###
GET http://127.0.0.1:8000/wishlist/1/
###

###
PATCH http://127.0.0.1:8000/wishlist/1/
Content-Type: application/json

{
  "producto_id": 3
}

###

DELETE http://127.0.0.1:8000/wishlist/all/1/


###

POST http://127.0.0.1:8000/api/categorias/crear/ HTTP/1.1
Content-Type: application/json

{
  "nombre": "caballero"
}


###

GET http://127.0.0.1:8000/api/categorias

###